sudo: required
dist: trusty
language: node_js
node_js: stable

notifications:
  email: false
  
cache:
  directories: node_modules

addons:
apt:
  sources:
    - google-chrome
#  packages:
#    - google-chrome-stable
#    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
#- npm install -g angular-cli
#- npm install -g karma
- npm install -g codecov
- npm install
- ng lint
- ng build
- ng serve & ng e2e


#- ng test --code-coverage --single-run #travis don't pass, 10minutes without message in console
script:
 - karma start karma.conf.js --single-run --code-coverage 
 - codecov
